package com.sx.pojo;

public class Userfile {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfile.fileid
     *
     * @mbg.generated Tue Sep 05 17:02:20 CST 2017
     */
    private Integer fileid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfile.filename
     *
     * @mbg.generated Tue Sep 05 17:02:20 CST 2017
     */
    private String filename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfile.filepath
     *
     * @mbg.generated Tue Sep 05 17:02:20 CST 2017
     */
    private String filepath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfile.id
     *
     * @mbg.generated Tue Sep 05 17:02:20 CST 2017
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfile.fileid
     *
     * @return the value of userfile.fileid
     *
     * @mbg.generated Tue Sep 05 17:02:20 CST 2017
     */
    public Integer getFileid() {
        return fileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfile.fileid
     *
     * @param fileid the value for userfile.fileid
     *
     * @mbg.generated Tue Sep 05 17:02:20 CST 2017
     */
    public void setFileid(Integer fileid) {
        this.fileid = fileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfile.filename
     *
     * @return the value of userfile.filename
     *
     * @mbg.generated Tue Sep 05 17:02:20 CST 2017
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfile.filename
     *
     * @param filename the value for userfile.filename
     *
     * @mbg.generated Tue Sep 05 17:02:20 CST 2017
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfile.filepath
     *
     * @return the value of userfile.filepath
     *
     * @mbg.generated Tue Sep 05 17:02:20 CST 2017
     */
    public String getFilepath() {
        return filepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfile.filepath
     *
     * @param filepath the value for userfile.filepath
     *
     * @mbg.generated Tue Sep 05 17:02:20 CST 2017
     */
    public void setFilepath(String filepath) {
        this.filepath = filepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfile.id
     *
     * @return the value of userfile.id
     *
     * @mbg.generated Tue Sep 05 17:02:20 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfile.id
     *
     * @param id the value for userfile.id
     *
     * @mbg.generated Tue Sep 05 17:02:20 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }
}